version: "3.7"

networks:
    TMSTEAM:

services:
  flask:
    build: ./flask
    restart: always
    volumes:
      - ./flask:/app
    networks:
      - TMSTEAM

  nginx:
    # build: ./nginx
    image: nginx:1.19-alpine
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      # - ./log/nginx:/var/log/nginx
      - ./nginx/public_site/site:/etc/nginx/conf.d
      - ./nginx/public_site/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - TMSTEAM      

